-- ====================================================================
-- GOVERNANCE APPLICATION LAYER - SECURITY POLICIES
-- ====================================================================
-- Data masking and row access policies for the governance application

USE SCHEMA GOV_APP.POLICIES;

-- Dynamic masking policy for sensitive data samples
CREATE OR REPLACE MASKING POLICY MASK_SENSITIVE_SAMPLES AS (VAL STRING) RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'DATA_STEWARD', 'AUDIT_ROLE') THEN VAL
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ANALYST') THEN 
      CASE 
        WHEN LEN(VAL) > 10 THEN CONCAT(LEFT(VAL, 3), '*****', RIGHT(VAL, 2))
        ELSE '***MASKED***'
      END
    ELSE '***MASKED***'
  END;

-- Masking policy for email addresses
CREATE OR REPLACE MASKING POLICY MASK_EMAIL AS (VAL STRING) RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'DATA_STEWARD') THEN VAL
    WHEN VAL IS NULL THEN NULL
    ELSE CONCAT('***', SPLIT_PART(VAL, '@', 2))
  END;

-- Masking policy for PII in evidence references
CREATE OR REPLACE MASKING POLICY MASK_EVIDENCE_REF AS (VAL STRING) RETURNS STRING ->
  CASE 
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'AUDIT_ROLE') THEN VAL
    WHEN CURRENT_ROLE() IN ('DATA_STEWARD', 'GOVERNANCE_ANALYST') THEN 
      REGEXP_REPLACE(VAL, '[0-9]{3,}', '***')
    ELSE 'RESTRICTED_ACCESS'
  END;

-- Row access policy for domain-based data segregation
CREATE OR REPLACE ROW ACCESS POLICY ROW_ACCESS_BY_DOMAIN AS (DOMAIN_NAME STRING) RETURNS BOOLEAN ->
  CASE 
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'AUDIT_ROLE') THEN TRUE
    WHEN CURRENT_ROLE() = 'RETAIL_DATA_ANALYST' AND DOMAIN_NAME = 'Retail' THEN TRUE
    WHEN CURRENT_ROLE() = 'LENDING_DATA_ANALYST' AND DOMAIN_NAME = 'Lending' THEN TRUE
    WHEN CURRENT_ROLE() = 'CARDS_DATA_ANALYST' AND DOMAIN_NAME = 'Cards' THEN TRUE
    WHEN CURRENT_ROLE() = 'DEPOSITS_DATA_ANALYST' AND DOMAIN_NAME = 'Deposits' THEN TRUE
    WHEN CURRENT_ROLE() IN ('DATA_STEWARD', 'GOVERNANCE_ANALYST') THEN TRUE
    ELSE FALSE
  END;

-- Row access policy for classification-based access control
CREATE OR REPLACE ROW ACCESS POLICY ROW_ACCESS_BY_CLASSIFICATION AS (CLASSIFICATION STRING) RETURNS BOOLEAN ->
  CASE 
    WHEN CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'AUDIT_ROLE') THEN TRUE
    WHEN CLASSIFICATION IN ('Public', 'Internal') THEN TRUE
    WHEN CLASSIFICATION = 'Confidential' AND CURRENT_ROLE() IN ('DATA_STEWARD', 'GOVERNANCE_ANALYST') THEN TRUE
    WHEN CLASSIFICATION = 'PII' AND CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'DATA_STEWARD', 'PRIVACY_OFFICER') THEN TRUE
    WHEN CLASSIFICATION = 'PCI' AND CURRENT_ROLE() IN ('GOVERNANCE_ADMIN', 'PCI_ANALYST') THEN TRUE
    ELSE FALSE
  END;

-- ====================================================================
-- APPLY POLICIES TO VIEWS
-- ====================================================================

-- Apply masking policies to sensitive columns in views
ALTER VIEW GOV_APP.VIEWS.VW_DQ_RESULTS_ENRICHED MODIFY COLUMN EVIDENCE_REF 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EVIDENCE_REF;

ALTER VIEW GOV_APP.VIEWS.VW_DQ_RESULTS_ENRICHED MODIFY COLUMN OWNER_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_CONTROL_RESULTS_ENRICHED MODIFY COLUMN OWNER_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_DATASET_OWNERS MODIFY COLUMN OWNER_EMAILS 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_BUSINESS_GLOSSARY MODIFY COLUMN STEWARD_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_DATA_CONTRACTS MODIFY COLUMN PRODUCER_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_DATA_CONTRACTS MODIFY COLUMN CONSUMER_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

ALTER VIEW GOV_APP.VIEWS.VW_RISK_DASHBOARD MODIFY COLUMN OWNER_EMAIL 
  SET MASKING POLICY GOV_APP.POLICIES.MASK_EMAIL;

-- Apply row access policies to views with domain information
ALTER VIEW GOV_APP.VIEWS.VW_TODAY_HEALTH 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_DOMAIN ON (DOMAIN_NAME);

ALTER VIEW GOV_APP.VIEWS.VW_DQ_RESULTS_ENRICHED 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_DOMAIN ON (DOMAIN_NAME);

ALTER VIEW GOV_APP.VIEWS.VW_DATASET_OWNERS 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_DOMAIN ON (DOMAIN_NAME);

ALTER VIEW GOV_APP.VIEWS.VW_BUSINESS_GLOSSARY 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_DOMAIN ON (DOMAIN_NAME);

ALTER VIEW GOV_APP.VIEWS.VW_DATA_CONTRACTS 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_DOMAIN ON (DOMAIN_NAME);

-- Apply classification-based row access policy where applicable
ALTER VIEW GOV_APP.VIEWS.VW_TODAY_HEALTH 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_CLASSIFICATION ON (CLASSIFICATION);

ALTER VIEW GOV_APP.VIEWS.VW_DQ_RESULTS_ENRICHED 
  ADD ROW ACCESS POLICY GOV_APP.POLICIES.ROW_ACCESS_BY_CLASSIFICATION ON (CLASSIFICATION);
